# Generated by Django 4.1.6 on 2023-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_customer_account_number_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
