# Generated by Django 4.1.6 on 2023-02-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_customer_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_number',
        ),
    ]
