# Generated by Django 4.1.6 on 2023-02-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_remove_customer_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
    ]
